---
- hosts: all
  user: vagrant
  tasks:
    - name: install rvm
      shell: "\\curl -L https://get.rvm.io | bash -s stable --ruby"
   
    - name: install jdk
      sudo: true
      apt: update_cache=yes
      apt: name=openjdk-7-jdk
   
    - name: make directory for lein
      file: state=directory path="/home/vagrant/bin"

    - name: install lein
      get_url: url="https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein" dest="/home/vagrant/bin/lein"

    - name: chmod lein to execute
      file: state=file path="/home/vagrant/bin/lein" mode=755
 
    - name: install git
      sudo: true
      apt: update_cache=yes
      apt: name=git
    
    - name: install zsh 
      sudo: true
      apt: name=zsh

    - name: install yadr
      command: 'sh -c "`curl -fsSL https://raw.github.com/skwp/dotfiles/master/install.sh`"'

    - name: config zshrc
      lineinfile: dest=/home/vagrant/.zshrc insertafter=EOF line="prompt_agnoster_setup"
